"""Initial schema.

Hand-written rather than autogenerated because the archive needs constructs
autogenerate does not emit: monthly declarative partitioning on
``lastfm_request``, content-addressed response keys, and the derived-table
invariants that make ``metaedit reindex`` reproducible.

Revision ID: 0001_initial
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ---------------------------------------------------------------- editor
    op.create_table(
        "snapshot",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("item_id", sa.String(64), nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("name", sa.Text()),
        sa.Column("fields", postgresql.JSONB(), nullable=False),
        sa.Column("etag", sa.Text()),
        sa.Column("date_last_saved", sa.DateTime(timezone=True)),
        sa.Column("source_op", sa.String(16), nullable=False),
        sa.Column("batch_id", sa.String(64)),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_snapshot_item_id", "snapshot", ["item_id"])
    op.create_index("ix_snapshot_batch_id", "snapshot", ["batch_id"])

    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("item_id", sa.String(64)),
        sa.Column("action", sa.String(32), nullable=False),
        sa.Column("changed_fields", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB()),
        sa.Column("lastfm_candidate", postgresql.JSONB()),
        sa.Column("lastfm_request_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("outcome", sa.String(16), nullable=False),
        sa.Column("error_code", sa.String(64)),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_audit_log_item_id", "audit_log", ["item_id"])

    # ----------------------------------------------------------- archive: raw
    op.create_table(
        "lastfm_response",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("body", postgresql.JSONB(), nullable=False),
        sa.Column("body_bytes", sa.Integer(), nullable=False),
        sa.Column("is_error", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("observation_count", sa.Integer(), nullable=False, server_default="1"),
    )

    op.create_table(
        "lastfm_request",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("method", sa.String(64), nullable=False),
        sa.Column("params", postgresql.JSONB(), nullable=False),
        sa.Column("params_hash", sa.String(64), nullable=False),
        sa.Column(
            "requested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column("http_status", sa.Integer()),
        sa.Column("lastfm_error_code", sa.Integer()),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("served_from_archive", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("user_agent", sa.Text()),
        sa.Column("api_key_fingerprint", sa.String(16)),
        sa.Column(
            "response_id", sa.String(64), sa.ForeignKey("lastfm_response.id", ondelete="RESTRICT")
        ),
        sa.PrimaryKeyConstraint("id", "requested_at", name="pk_lastfm_request"),
        postgresql_partition_by="RANGE (requested_at)",
    )
    op.create_index("idx_lastfm_request_params_hash", "lastfm_request", ["params_hash"])
    op.create_index("idx_lastfm_request_response_id", "lastfm_request", ["response_id"])
    op.create_index("idx_lastfm_request_method_time", "lastfm_request", ["method", "requested_at"])

    # ------------------------------------------------------ archive: derived
    _create_entity_tables()
    _create_graph_tables()

    op.create_table(
        "archive_stat",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column(
            "measured_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("payload_bytes", sa.BigInteger(), nullable=False),
        sa.Column("request_rows", sa.BigInteger(), nullable=False),
        sa.Column("response_rows", sa.BigInteger(), nullable=False),
        sa.Column("observations", sa.BigInteger(), nullable=False),
        sa.Column("oldest_request_at", sa.DateTime(timezone=True)),
        sa.Column("cap_bytes", sa.BigInteger(), nullable=False),
    )


def _create_entity_tables() -> None:
    op.create_table(
        "lastfm_artist",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("identity", sa.Text(), nullable=False),
        sa.Column("mbid", sa.String(64)),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_norm", sa.Text(), nullable=False),
        sa.Column("url", sa.Text()),
        sa.Column("listeners", sa.BigInteger()),
        sa.Column("playcount", sa.BigInteger()),
        sa.Column("overview", sa.Text()),
        sa.Column("bio_published", sa.Text()),
        sa.Column("images", postgresql.JSONB()),
        sa.Column("tags", postgresql.JSONB()),
        sa.Column("stats", postgresql.JSONB()),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_request_id", sa.BigInteger()),
        sa.Column("latest_response_id", sa.String(64), nullable=False),
        sa.UniqueConstraint("identity", name="uq_lastfm_artist_identity"),
    )
    op.create_index("ix_lastfm_artist_mbid", "lastfm_artist", ["mbid"])
    op.create_index("idx_lastfm_artist_name_norm", "lastfm_artist", ["name_norm"])

    op.create_table(
        "lastfm_album",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("identity", sa.Text(), nullable=False),
        sa.Column("mbid", sa.String(64)),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_norm", sa.Text(), nullable=False),
        sa.Column("artist_name", sa.Text()),
        sa.Column("artist_name_norm", sa.Text()),
        sa.Column("url", sa.Text()),
        sa.Column("listeners", sa.BigInteger()),
        sa.Column("playcount", sa.BigInteger()),
        sa.Column("releasedate", sa.Text()),
        sa.Column("production_year", sa.Integer()),
        sa.Column("images", postgresql.JSONB()),
        sa.Column("tags", postgresql.JSONB()),
        sa.Column("tracklist", postgresql.JSONB()),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_request_id", sa.BigInteger()),
        sa.Column("latest_response_id", sa.String(64), nullable=False),
        sa.UniqueConstraint("identity", name="uq_lastfm_album_identity"),
    )
    op.create_index("ix_lastfm_album_mbid", "lastfm_album", ["mbid"])
    op.create_index("idx_lastfm_album_name_norm", "lastfm_album", ["name_norm"])
    op.create_index("idx_lastfm_album_artist_norm", "lastfm_album", ["artist_name_norm"])

    op.create_table(
        "lastfm_track",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("identity", sa.Text(), nullable=False),
        sa.Column("mbid", sa.String(64)),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_norm", sa.Text(), nullable=False),
        sa.Column("artist_name", sa.Text()),
        sa.Column("artist_name_norm", sa.Text()),
        sa.Column("artist_mbid", sa.String(64)),
        sa.Column("album_name", sa.Text()),
        sa.Column("album_mbid", sa.String(64)),
        sa.Column("album_position", sa.Integer()),
        sa.Column("url", sa.Text()),
        sa.Column("duration_ms", sa.BigInteger()),
        sa.Column("listeners", sa.BigInteger()),
        sa.Column("playcount", sa.BigInteger()),
        sa.Column("overview", sa.Text()),
        sa.Column("wiki_published", sa.Text()),
        sa.Column("tags", postgresql.JSONB()),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_request_id", sa.BigInteger()),
        sa.Column("latest_response_id", sa.String(64), nullable=False),
        sa.UniqueConstraint("identity", name="uq_lastfm_track_identity"),
    )
    op.create_index("ix_lastfm_track_mbid", "lastfm_track", ["mbid"])
    op.create_index("idx_lastfm_track_name_norm", "lastfm_track", ["name_norm"])
    op.create_index("idx_lastfm_track_artist_norm", "lastfm_track", ["artist_name_norm"])


def _create_graph_tables() -> None:
    op.create_table(
        "lastfm_tag_edge",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("entity_kind", sa.String(16), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_name", sa.Text(), nullable=False),
        sa.Column("tag_name_norm", sa.Text(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer()),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_response_id", sa.String(64), nullable=False),
        sa.UniqueConstraint("entity_kind", "entity_id", "tag_name_norm", name="uq_lastfm_tag_edge"),
    )
    op.create_index("idx_lastfm_tag_edge_tag", "lastfm_tag_edge", ["tag_name_norm"])

    op.create_table(
        "lastfm_similarity",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column(
            "artist_id",
            sa.BigInteger(),
            sa.ForeignKey("lastfm_artist.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("peer_name", sa.Text(), nullable=False),
        sa.Column("peer_name_norm", sa.Text(), nullable=False),
        sa.Column("peer_mbid", sa.String(64)),
        sa.Column("peer_artist_id", sa.BigInteger()),
        sa.Column("match", sa.Numeric(5, 4)),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_response_id", sa.String(64), nullable=False),
        sa.UniqueConstraint("artist_id", "peer_name_norm", name="uq_lastfm_similarity"),
    )
    op.create_index("idx_lastfm_similarity_peer", "lastfm_similarity", ["peer_name_norm"])

    op.create_table(
        "lastfm_artist_alias",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("requested_name_norm", sa.Text(), nullable=False),
        sa.Column("canonical_artist_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("requested_name_norm", name="uq_lastfm_artist_alias"),
    )

    op.create_table(
        "lastfm_entity_tag",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("tag_name", sa.Text(), nullable=False),
        sa.Column("tag_name_norm", sa.Text(), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("tag_name_norm", name="uq_lastfm_entity_tag"),
    )


def downgrade() -> None:
    for table in (
        "lastfm_entity_tag",
        "lastfm_artist_alias",
        "lastfm_similarity",
        "lastfm_tag_edge",
        "lastfm_track",
        "lastfm_album",
        "lastfm_artist",
        "archive_stat",
        "lastfm_request",
        "lastfm_response",
        "audit_log",
        "snapshot",
    ):
        op.drop_table(table)
