"""Add the genre_blacklist table.

Operator-editable policy: genres that must never be proposed for writing. Until now the
blacklist was env-var only (``TAG_BLACKLIST_EXTRA``), which meant changing it required
editing compose config and restarting the container.

``value_norm`` is unique, mirroring the argument ``lastfm_tag_edge`` makes about
``(entity, tag_name_norm)``: without folding, ``Rock`` and ``rock`` would occupy two rows
and the second would silently do nothing. Parsing already deduplicates
case-insensitively; this constraint is the backstop for a caller that skips the parser.

**Autogenerate was used and then hand-corrected.** It emitted ``op.drop_table`` calls for
every ``lastfm_request_YYYY_MM`` partition, because those are created at runtime by
``metaedit.db.partitions`` rather than declared on the model, so autogenerate reads them
as tables to remove. Applying that output would have deleted the entire archived request
log. The drops are removed here, and there is no ``include_object`` hook to stop it
happening again -- so the next autogenerated revision needs the same review.

Revision ID: 0003_genre_blacklist
Revises: 0002_album_overview
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_genre_blacklist"
down_revision: str | None = "0002_album_overview"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "genre_blacklist",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        # As the operator typed it. "Rock" and "rock" are one entry, and echoing the
        # folded form back to someone who typed the capitalised one reads as a bug.
        sa.Column("value", sa.Text(), nullable=False),
        # normalize_tag(value) -- comparison key and uniqueness key.
        sa.Column("value_norm", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value_norm", name="uq_genre_blacklist_value_norm"),
    )


def downgrade() -> None:
    op.drop_table("genre_blacklist")
