/**
 * The single HTTP boundary of the SPA.
 *
 * The browser only ever talks to our own /api origin: the Jellyfin admin key and the
 * Last.fm key stay server-side and are never exposed here.
 */

export interface ApiErrorBody {
  error?: { code?: string; message?: string; retryable?: boolean; current?: unknown }
}

export class ApiError extends Error {
  readonly status: number
  readonly code: string
  readonly retryable: boolean

  constructor(status: number, code: string, message: string, retryable = false) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.code = code
    this.retryable = retryable
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, {
    ...init,
    headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) },
  })

  if (!response.ok) {
    let code = `http_${response.status}`
    let message = response.statusText || 'Request failed'
    let retryable = false
    try {
      const body = (await response.json()) as ApiErrorBody
      if (body.error?.code) code = body.error.code
      if (body.error?.message) message = body.error.message
      retryable = Boolean(body.error?.retryable)
    } catch {
      // Non-JSON error body; the status-based defaults stand.
    }
    throw new ApiError(response.status, code, message, retryable)
  }

  if (response.status === 204) return undefined as T
  return (await response.json()) as T
}

/**
 * Read a Server-Sent Events response.
 *
 * The bulk endpoints stream rather than returning one payload, because a run over
 * hundreds of items is long and partly irreversible: progress has to be visible per
 * item, so a failure is reported where it happened rather than at the end.
 */
async function stream<T>(
  path: string,
  body: unknown,
  onEvent: (event: T) => void,
  signal?: AbortSignal,
): Promise<void> {
  const response = await fetch(path, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    ...(signal ? { signal } : {}),
  })

  if (!response.ok) {
    let code = `http_${response.status}`
    let message = response.statusText || 'Request failed'
    try {
      const payload = (await response.json()) as ApiErrorBody
      if (payload.error?.code) code = payload.error.code
      if (payload.error?.message) message = payload.error.message
    } catch {
      // keep the defaults
    }
    throw new ApiError(response.status, code, message)
  }
  if (!response.body) throw new ApiError(500, 'no_stream', 'The response had no body')

  const reader = response.body.getReader()
  const decoder = new TextDecoder()
  let buffer = ''

  // SSE frames are separated by a blank line, and a frame can span reads.
  for (;;) {
    const { done, value } = await reader.read()
    if (done) break
    buffer += decoder.decode(value, { stream: true })
    const frames = buffer.split('\n\n')
    buffer = frames.pop() ?? ''
    for (const frame of frames) {
      for (const line of frame.split('\n')) {
        if (!line.startsWith('data: ')) continue
        try {
          onEvent(JSON.parse(line.slice(6)) as T)
        } catch {
          // A malformed frame is not worth aborting a running batch over.
        }
      }
    }
  }
}

// ---------------------------------------------------------------------- types
//
// Derived from the backend's own OpenAPI document (`schema.gen.ts`, regenerated by
// `scripts/export_contract.py`). These are aliases rather than hand-written
// interfaces on purpose: a hand-written copy of a contract drifts from it silently,
// and the previous version of this file described a diff shape the server had already
// stopped returning.

import type { components, paths } from './schema.gen'

type Schemas = components['schemas']

export type LibraryInfo = Schemas['LibraryInfo']
export type ItemSummary = Schemas['ItemSummary']
export type ItemSummaryPage = Schemas['ItemSummaryPage']
export type InfoResponse = Schemas['InfoResponse']
export type JellyfinInfo = Schemas['JellyfinInfo']
export type ArchiveInfo = Schemas['ArchiveInfo']
export type LastfmInfo = Schemas['LastfmInfo']

export type ArchiveStats = Schemas['ArchiveStatsResponse']
export type ReadMetricsView = Schemas['ReadMetricsView']
export type DerivedCounts = Schemas['DerivedCounts']
export type PartitionUsage = Schemas['PartitionUsage']
export type ReindexResponse = Schemas['ReindexResponse']
export type ReindexCounts = Schemas['ReindexCounts']

export type ConfidenceView = Schemas['ConfidenceView']
export type ConfidenceComponent = Schemas['ConfidenceComponentView']
export type CandidateView = Schemas['CandidateView']
export type CandidatesResponse = Schemas['CandidatesResponse']
export type CandidateTagView = Schemas['CandidateTagView']

export type FieldChangeView = Schemas['FieldChangeView']
export type DiffResponse = Schemas['DiffResponse']
export type CandidateSummary = Schemas['CandidateSummary']
export type ApplyResponse = Schemas['ApplyResponse']
export type SnapshotSummary = Schemas['SnapshotSummary']
export type SnapshotListResponse = Schemas['SnapshotListResponse']

export type ArchiveEntitySummary = Schemas['ArchiveEntitySummary']
export type ArchiveEntityDetail = Schemas['ArchiveEntityDetail']
export type ArchiveEntityListResponse = Schemas['ArchiveEntityListResponse']
export type ArchiveTagView = Schemas['ArchiveTagView']
export type ArchiveTagCountView = Schemas['ArchiveTagCountView']
export type ArchiveTagListResponse = Schemas['ArchiveTagListResponse']
export type ArchiveSimilarityView = Schemas['ArchiveSimilarityView']
export type ArchiveAliasView = Schemas['ArchiveAliasView']
export type ArchiveAliasListResponse = Schemas['ArchiveAliasListResponse']

export type BulkJobSummary = Schemas['BulkJobSummary']
export type BulkJobListResponse = Schemas['BulkJobListResponse']

// The SSE event union. The backend declares the individual frames; the discriminated
// union is assembled here because that is what a consumer switches on.
export type BulkItemEvent = Schemas['BulkItemEvent']
export type BulkAppliedEvent = Schemas['BulkAppliedEvent']
export type BulkFailedEvent = Schemas['BulkFailedEvent']
export type BulkRevertedEvent = Schemas['BulkRevertedEvent']
export type BulkSummaryEvent = Schemas['BulkSummaryEvent']
export type BulkErrorEvent = Schemas['BulkErrorEvent']

// Harvest events, likewise generated from the backend's stream schemas.
export type HarvestItemEvent = Schemas['HarvestItemEvent']
export type HarvestSummaryEvent = Schemas['HarvestSummaryEvent']
export type HarvestReindexedEvent = Schemas['HarvestReindexedEvent']
export type HarvestErrorEvent = Schemas['HarvestErrorEvent']
export type HarvestSearchAlternative = Schemas['HarvestSearchAlternative']

export type HarvestEvent =
  | HarvestItemEvent
  | HarvestSummaryEvent
  | HarvestReindexedEvent
  | HarvestErrorEvent
  | { type: 'done' }

export type BulkEvent =
  | BulkItemEvent
  | BulkAppliedEvent
  | BulkFailedEvent
  | BulkRevertedEvent
  | BulkSummaryEvent
  | BulkErrorEvent
  | { type: 'done' }

export type SelectionKind = 'artist' | 'album' | 'song'

export interface BulkSelectionInput {
  kind: 'artist' | 'album' | 'song'
  ids?: string[]
  parent_id?: string | null
  search?: string | null
  limit?: number
  missing_metadata?: boolean
}

// ------------------------------------------------------- typed query helpers
//
// Bodies were already typed, but query strings were built by hand — which is how the
// library page came to send `limit` to an endpoint that takes `page_size` and silently
// received the default page every time. Deriving the query type from the same document
// makes a wrong parameter name a compile error.

export type ItemsQuery = NonNullable<paths['/api/items']['get']['parameters']['query']>
export type ArchiveEntitiesQuery = NonNullable<
  paths['/api/archive/entities']['get']['parameters']['query']
>
export type ArchiveTagsQuery = NonNullable<
  paths['/api/archive/tags']['get']['parameters']['query']
>

export function queryString(params: Record<string, unknown>): string {
  const search = new URLSearchParams()
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null || value === '') continue
    // Arrays become repeated parameters (`?missing=genres&missing=tags`), which is how
    // FastAPI takes a list. `set` would send one comma-joined value, and the API answers
    // that with a 422 rather than quietly filtering by nothing -- but a 422 from a filter
    // that looks applied is exactly the kind of failure worth not creating.
    if (Array.isArray(value)) {
      for (const entry of value) {
        if (entry !== undefined && entry !== null && entry !== '') search.append(key, String(entry))
      }
      continue
    }
    search.set(key, String(value))
  }
  const rendered = search.toString()
  return rendered ? `?${rendered}` : ''
}

export const api = {
  get: <T>(path: string) => request<T>(path),
  items: (query: ItemsQuery) => request<ItemSummaryPage>(`/api/items${queryString(query)}`),
  archiveEntities: (query: ArchiveEntitiesQuery) =>
    request<ArchiveEntityListResponse>(`/api/archive/entities${queryString(query)}`),
  archiveTags: (query: ArchiveTagsQuery) =>
    request<ArchiveTagListResponse>(`/api/archive/tags${queryString(query)}`),
  post: <T>(path: string, body?: unknown) => {
    const init: RequestInit = { method: 'POST' }
    if (body !== undefined) init.body = JSON.stringify(body)
    return request<T>(path, init)
  },
  stream,
}

export { stream as streamEvents }
