/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/archive/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Archive Aliases
         * @description Last.fm autocorrect corrections, so a known misspelling skips a request.
         */
        get: operations["archive_aliases_api_archive_aliases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Archive Diagnose
         * @description What is archived, and what the derivation cannot use.
         *
         *     The counterpart to the CLI's ``archive-entities``: a parsing regression appears
         *     as ``shapes.unexpected`` rising above zero, with the offending methods named.
         */
        get: operations["archive_diagnose_api_archive_diagnose_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Archive Entities
         * @description Search the derived layer offline.
         *
         *     Reads what the derivation produced and never touches the network: this is what
         *     answers "what do I already know about X" without spending a request.
         */
        get: operations["archive_entities_api_archive_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/entities/{kind}/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive Entity */
        get: operations["archive_entity_api_archive_entities__kind___entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Reindex
         * @description Rebuild the derived layer from the raw archive.
         *
         *     ``dry_run`` defaults to **true** here, unlike the CLI: an HTTP client should not
         *     be able to rebuild the structured layer by accident, and the report is what a UI
         *     wants in either case.
         */
        post: operations["run_reindex_api_archive_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive Stats */
        get: operations["archive_stats_api_archive_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Archive Tags
         * @description Every tag across the archive, with how many distinct entities carry it.
         */
        get: operations["archive_tags_api_archive_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Apply
         * @description Apply a reviewed job, streaming progress and isolating failures per item.
         *
         *     ``confirm`` must be true. The job must exist, which means a diff was reviewed in
         *     this process: a bulk write is never the first request of a session.
         */
        post: operations["bulk_apply_api_bulk_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Diff
         * @description Diff every item in the selection, streaming one event per item.
         *
         *     **Writes nothing.** The job id in the summary event is what a later ``/bulk/apply``
         *     must present, so an apply can never be the first thing that happens.
         */
        post: operations["bulk_diff_api_bulk_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Reviewed diffs still available to apply, newest last.
         *
         *     Exposed because "which batch am I about to apply" should be answerable before an
         *     apply, not discovered afterwards.
         */
        get: operations["list_jobs_api_bulk_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/{batch_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Revert
         * @description Undo every item written by a batch, oldest first, isolating failures.
         *
         *     The batch id lives on the snapshots, so this works after a restart even though the
         *     diff job that produced it does not.
         */
        post: operations["bulk_revert_api_bulk__batch_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Harvest Batch
         * @description Fetch and archive Last.fm data for a selection, streaming per-item outcomes.
         *
         *     Writes nothing to Jellyfin. Items are reported as they complete, so a run over a
         *     large selection shows progress rather than appearing to hang, and an item that
         *     cannot be found is reported without stopping the batch.
         */
        post: operations["harvest_batch_api_harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Dependency-free liveness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: report each dependency independently so partial failures are visible.
         */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_api_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Items
         * @description Browse one media type, ordered and narrowed.
         *
         *     `sort` is validated against an allow-list rather than passed through. Live-verified
         *     on 12.2.0: an unrecognised `sortBy` is accepted and *silently ignored*, so a
         *     pass-through would let the UI present items in one order while claiming another.
         */
        get: operations["items_api_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Item States
         * @description Hydrate many items at once -- the multi-select path for bulk editing.
         */
        post: operations["item_states_api_items_states_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Item Apply
         * @description Apply a reviewed change set.
         *
         *     ``confirm`` must be true. A write is never the default outcome of a request, and
         *     an omitted selection means the plan's default -- which is empty for anything that
         *     needs review, so an unreviewed match writes nothing.
         */
        post: operations["item_apply_api_items__item_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Item Candidates
         * @description Archived Last.fm entities that could be this item, best match first.
         *
         *     Reads only; nothing is fetched and nothing is written.
         */
        post: operations["item_candidates_api_items__item_id__candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Item Diff
         * @description Preview the exact changes applying this candidate would make.
         *
         *     Everything is computed and returned; nothing is written. The response includes
         *     the withheld fields and the reasons, so a policy can be debugged rather than
         *     guessed at.
         */
        post: operations["item_diff_api_items__item_id__diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Harvest One
         * @description Fetch and archive Last.fm data for one item.
         *
         *     Reads Jellyfin, spends Last.fm requests, writes nothing to Jellyfin. A miss is a
         *     reported outcome with search alternatives, not an error status.
         */
        post: operations["harvest_one_api_items__item_id__harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Item
         * @description Ask Jellyfin to re-run *its* metadata providers for one item.
         *
         *     Deliberately separate from applying our edits: this is Jellyfin's pipeline,
         *     not ours, and it can overwrite values we just wrote.
         */
        post: operations["refresh_item_api_items__item_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Item Snapshots
         * @description Snapshot history, newest first, so any applied change can be undone.
         */
        get: operations["item_snapshots_api_items__item_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item State */
        get: operations["item_state_api_items__item_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Libraries */
        get: operations["libraries_api_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert
         * @description Restore the values captured by a snapshot.
         *
         *     A revert is an ordinary write built from the snapshot's fields, and it is itself
         *     snapshotted -- so undoing an undo works and history is never mutated.
         */
        post: operations["revert_api_snapshots__snapshot_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyRequest */
        ApplyRequest: {
            /**
             * Confirm
             * @description must be true: a write is never the default outcome of a request
             * @default false
             */
            confirm: boolean;
            /**
             * Entity Id
             * @description id of the archived entity to map from
             */
            entity_id: number;
            /**
             * Entity Kind
             * @description defaults to the kind implied by the Jellyfin item
             */
            entity_kind?: ("artist" | "album" | "track") | null;
            /**
             * Expected Etag
             * @description the etag the diff was prepared against; a mismatch is refused
             */
            expected_etag?: string | null;
            /**
             * Fields
             * @description fields to write; omit to use the plan's default selection
             */
            fields?: string[] | null;
            /** Overrides */
            overrides?: components["schemas"]["FieldPolicyOverride"][];
            tag_policy?: components["schemas"]["TagPolicyRequest"] | null;
        };
        /** ApplyResponse */
        ApplyResponse: {
            /** Applied */
            applied: string[];
            /** Duration Ms */
            duration_ms: number;
            /** Etag After */
            etag_after: string | null;
            /** Etag Before */
            etag_before: string | null;
            /** Idempotency Key */
            idempotency_key: string | null;
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Snapshot Id */
            snapshot_id: number | null;
            /** State */
            state: {
                [key: string]: unknown;
            } | null;
            /** Unchanged */
            unchanged: string[];
        };
        /** ArchiveAliasListResponse */
        ArchiveAliasListResponse: {
            /** Aliases */
            aliases: components["schemas"]["ArchiveAliasView"][];
            /** Total */
            total: number;
        };
        /**
         * ArchiveAliasView
         * @description A recorded Last.fm autocorrect.
         *
         *     ``requested`` is the normalised name as asked, ``canonical_name`` what Last.fm
         *     answered with, so a known misspelling can skip a request next time.
         */
        ArchiveAliasView: {
            /** Canonical Artist Id */
            canonical_artist_id: number | null;
            /** Canonical Name */
            canonical_name: string | null;
            /** Kind */
            kind: string | null;
            /** Requested */
            requested: string;
        };
        /**
         * ArchiveEntityDetail
         * @description One entity, with tags and similarity expanded.
         *
         *     Deliberately *not* a subclass of the summary. Its ``tags`` are objects with rank and
         *     count where the summary's are strings, and narrowing a field's type in a subclass is
         *     not a legal override -- mypy rejected it, which is the correct answer rather than an
         *     inconvenience. Two shapes that differ this much are two models.
         */
        ArchiveEntityDetail: {
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
            /** First Seen At */
            first_seen_at: string | null;
            /** Id */
            id: number;
            /** Identity */
            identity: string;
            /** Kind */
            kind: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Latest Response Id */
            latest_response_id: string;
            /** Listeners */
            listeners: number | null;
            /** Mbid */
            mbid: string | null;
            /** Name */
            name: string;
            /** Overview */
            overview: string | null;
            /** Playcount */
            playcount: number | null;
            /** Similar */
            similar: components["schemas"]["ArchiveSimilarityView"][];
            /** Tags */
            tags: components["schemas"]["ArchiveTagView"][];
            /** Url */
            url: string | null;
        };
        /**
         * ArchiveEntityListResponse
         * @description A page of archived entities.
         *
         *     The field names match what the endpoint has always returned. Writing them from
         *     memory instead of reading the code produced a model that rejected every real
         *     response -- which is precisely why these shapes are worth declaring.
         */
        ArchiveEntityListResponse: {
            /** Items */
            items: components["schemas"]["ArchiveEntitySummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ArchiveEntitySummary
         * @description A list row: tags are bare names, because the list has no room for counts.
         */
        ArchiveEntitySummary: {
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
            /** First Seen At */
            first_seen_at: string | null;
            /** Id */
            id: number;
            /** Identity */
            identity: string;
            /** Kind */
            kind: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Latest Response Id */
            latest_response_id: string;
            /** Listeners */
            listeners: number | null;
            /** Mbid */
            mbid: string | null;
            /** Name */
            name: string;
            /** Overview */
            overview: string | null;
            /** Playcount */
            playcount: number | null;
            /** Tags */
            tags: string[];
            /** Url */
            url: string | null;
        };
        /** ArchiveInfo */
        ArchiveInfo: {
            /** Cap Bytes */
            cap_bytes: number;
            /** Enabled */
            enabled: boolean;
            /** Log Requests */
            log_requests: boolean;
        };
        /** ArchiveSimilarityView */
        ArchiveSimilarityView: {
            /** Match */
            match: number | null;
            /** Mbid */
            mbid: string | null;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
        };
        /** ArchiveStatsResponse */
        ArchiveStatsResponse: {
            /** Cap Bytes */
            cap_bytes: number;
            derived: components["schemas"]["DerivedCounts"];
            /** Headroom Bytes */
            headroom_bytes: number;
            /** Observations */
            observations: number;
            /** Oldest Request At */
            oldest_request_at: string | null;
            /** Partitions */
            partitions: components["schemas"]["PartitionUsage"][];
            /** Payload Bytes */
            payload_bytes: number;
            reads: components["schemas"]["ReadMetricsView"];
            /** Request Rows */
            request_rows: number;
            /** Response Rows */
            response_rows: number;
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "warning" | "cap_reached";
            /** Stray Archive Reads */
            stray_archive_reads: number;
            /** Used Ratio */
            used_ratio: number;
            /** Warn Bytes */
            warn_bytes: number;
        };
        /** ArchiveTagCountView */
        ArchiveTagCountView: {
            /** Entity Count */
            entity_count: number;
            /** Name */
            name: string;
            /** Norm */
            norm: string | null;
        };
        /** ArchiveTagListResponse */
        ArchiveTagListResponse: {
            /** Tags */
            tags: components["schemas"]["ArchiveTagCountView"][];
            /** Total */
            total: number;
        };
        /** ArchiveTagView */
        ArchiveTagView: {
            /** Count */
            count: number | null;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
        };
        /** Body_harvest_one_api_items__item_id__harvest_post */
        Body_harvest_one_api_items__item_id__harvest_post: {
            /**
             * Search Fallback
             * @default true
             */
            search_fallback: boolean;
        };
        /** BulkAppliedEvent */
        BulkAppliedEvent: {
            /** Applied Fields */
            applied_fields: string[];
            /** Index */
            index: number;
            /** Item Id */
            item_id: string;
            /** Name */
            name: string;
            /** Snapshot Id */
            snapshot_id: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "applied";
        };
        /** BulkApplyRequest */
        BulkApplyRequest: {
            /**
             * Confirm
             * @description must be true
             * @default false
             */
            confirm: boolean;
            /**
             * Fields
             * @description fields to write for every item; omit to use each item's default selection, which is empty for anything needing review
             */
            fields?: string[] | null;
            /**
             * Job Id
             * @description from a /bulk/diff run
             */
            job_id: string;
            /**
             * Selections
             * @description per-item fields, keyed by item id. This is what review produces: an album and an artist do not share a field set, so one list for both would either write a field an item should not change or skip one it should. An item absent from the map writes nothing.
             */
            selections?: {
                [key: string]: string[];
            } | null;
        };
        /** BulkDiffRequest */
        BulkDiffRequest: {
            /**
             * Min Confidence
             * @description skip items whose best candidate scores below this
             * @default 0
             */
            min_confidence: number;
            /** Overrides */
            overrides?: components["schemas"]["FieldPolicyOverride"][];
            /**
             * @default {
             *       "kind": "artist",
             *       "limit": 50,
             *       "missing_metadata": false
             *     }
             */
            selection: components["schemas"]["BulkSelection"];
            tag_policy?: components["schemas"]["TagPolicyRequest"] | null;
        };
        /** BulkErrorEvent */
        BulkErrorEvent: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /** BulkFailedEvent */
        BulkFailedEvent: {
            /** Error */
            error: string;
            /** Error Code */
            error_code: string | null;
            /** Index */
            index: number | null;
            /** Item Id */
            item_id: string;
            /** Name */
            name: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "failed";
        };
        /** BulkItemEvent */
        BulkItemEvent: {
            /** Applicable */
            applicable: boolean;
            diff: components["schemas"]["DiffResponse"];
            /** Index */
            index: number;
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Skipped Reason */
            skipped_reason: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "item";
        };
        /** BulkJobListResponse */
        BulkJobListResponse: {
            /** Count */
            count: number;
            /** Jobs */
            jobs: components["schemas"]["BulkJobSummary"][];
        };
        /** BulkJobSummary */
        BulkJobSummary: {
            /** Applicable */
            applicable: number;
            /** Applied */
            applied: boolean;
            /** Batch Id */
            batch_id: string;
            /** Created At */
            created_at: string;
            /** Items */
            items: number;
            /** Job Id */
            job_id: string;
            /** Skipped */
            skipped: number;
        };
        /** BulkRevertedEvent */
        BulkRevertedEvent: {
            /** Item Id */
            item_id: string;
            /** Restored Fields */
            restored_fields: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reverted";
        };
        /**
         * BulkSelection
         * @description Which items, and nothing else. The fields to write are chosen after review.
         */
        BulkSelection: {
            /**
             * Ids
             * @description explicit item ids, if known
             */
            ids?: string[] | null;
            /**
             * Kind
             * @default artist
             * @enum {string}
             */
            kind: "artist" | "album" | "song";
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Missing Metadata
             * @description only items lacking genres, provider ids or an overview
             * @default false
             */
            missing_metadata: boolean;
            /** Parent Id */
            parent_id?: string | null;
            /** Search */
            search?: string | null;
        };
        /** BulkSummaryEvent */
        BulkSummaryEvent: {
            /** Applicable */
            applicable: number | null;
            /** Applied */
            applied: number | null;
            /** Batch Id */
            batch_id: string | null;
            /** Batch Revert */
            batch_revert: string | null;
            /** Failed */
            failed: number | null;
            /** Failures */
            failures: {
                [key: string]: unknown;
            }[];
            /** Items */
            items: number | null;
            /** Job Id */
            job_id: string | null;
            /** Reverted */
            reverted: number | null;
            /** Skipped */
            skipped: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "summary";
        };
        /** CandidateSummary */
        CandidateSummary: {
            /** Artist */
            artist: string | null;
            /** Mbid */
            mbid: string | null;
            /** Name */
            name: string;
            /** Response Id */
            response_id: string | null;
            /** Url */
            url: string | null;
            /** Year */
            year: number | null;
        };
        /** CandidateTagView */
        CandidateTagView: {
            /** Count */
            count: number | null;
            /** Name */
            name: string;
        };
        /** CandidateView */
        CandidateView: {
            /** Artist */
            artist: string | null;
            confidence: components["schemas"]["ConfidenceView"];
            /** Duration Ms */
            duration_ms: number | null;
            /** Entity Id */
            entity_id: number;
            /**
             * Entity Kind
             * @enum {string}
             */
            entity_kind: "artist" | "album" | "track";
            /**
             * Has Overview
             * @default false
             */
            has_overview: boolean;
            /** Identity */
            identity: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Latest Response Id */
            latest_response_id: string | null;
            /** Listeners */
            listeners: number | null;
            /**
             * Matched On
             * @enum {string}
             */
            matched_on: "mbid" | "name";
            /** Mbid */
            mbid: string | null;
            /** Name */
            name: string;
            /** Playcount */
            playcount: number | null;
            /** Tags */
            tags: components["schemas"]["CandidateTagView"][];
            /** Url */
            url: string | null;
            /** Year */
            year: number | null;
        };
        /** CandidatesRequest */
        CandidatesRequest: {
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Refresh
             * @description Reserved: fetching from Last.fm is not part of the read-only diff path.
             * @default false
             */
            refresh: boolean;
        };
        /** CandidatesResponse */
        CandidatesResponse: {
            /** Candidates */
            candidates: components["schemas"]["CandidateView"][];
            /** Count */
            count: number;
            /** Etag */
            etag: string | null;
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Note */
            note: string;
        };
        /**
         * ConfidenceComponentView
         * @description One weighted component of a match score, with its contribution.
         */
        ConfidenceComponentView: {
            /** Applied Weight */
            applied_weight: number;
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** ConfidenceView */
        ConfidenceView: {
            /** Accepts By Default */
            accepts_by_default: boolean;
            /** Components */
            components: components["schemas"]["ConfidenceComponentView"][];
            /** Mbid Conflict */
            mbid_conflict: boolean;
            /** Notes */
            notes: string[];
            /** Total */
            total: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "auto" | "review" | "reject";
        };
        /** DerivedCounts */
        DerivedCounts: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Newest Observation At */
            newest_observation_at: string | null;
            /** Total */
            total: number;
        };
        /** DiffRequest */
        DiffRequest: {
            /**
             * Entity Id
             * @description id of the archived entity to map from
             */
            entity_id: number;
            /**
             * Entity Kind
             * @description defaults to the kind implied by the Jellyfin item
             */
            entity_kind?: ("artist" | "album" | "track") | null;
            /** Overrides */
            overrides?: components["schemas"]["FieldPolicyOverride"][];
            tag_policy?: components["schemas"]["TagPolicyRequest"] | null;
        };
        /** DiffResponse */
        DiffResponse: {
            candidate: components["schemas"]["CandidateSummary"];
            /** Changes */
            changes: components["schemas"]["FieldChangeView"][];
            confidence: components["schemas"]["ConfidenceView"];
            /** Default Selection */
            default_selection: string[];
            /** Etag */
            etag: string | null;
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Locked Fields */
            locked_fields: string[];
            /** Name */
            name: string;
            /** Withheld */
            withheld: components["schemas"]["FieldChangeView"][];
        };
        /**
         * FieldChangeView
         * @description One proposed change to one writable field.
         */
        FieldChangeView: {
            /** Changes Anything */
            changes_anything: boolean;
            /** Current */
            current: unknown;
            /** Field */
            field: string;
            /** Mode */
            mode: string;
            /** Proposed */
            proposed: unknown;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Selected */
            selected: boolean;
            /** Source */
            source: string;
            /** Withheld Reason */
            withheld_reason: string | null;
        };
        /**
         * FieldPolicyOverride
         * @description Per-field mode for one request, so a single edit need not change configuration.
         */
        FieldPolicyOverride: {
            /** Field */
            field: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "keep_existing" | "fill_if_empty" | "replace" | "merge";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarvestErrorEvent */
        HarvestErrorEvent: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /**
         * HarvestItemEvent
         * @description One harvested item, as a stream frame.
         *
         *     Carries the same fields as ``HarvestItemResponse`` plus the stream's position, so the
         *     batch event and the single-item response cannot describe different things.
         */
        HarvestItemEvent: {
            /** Alternatives */
            alternatives: components["schemas"]["HarvestSearchAlternative"][];
            /** Derived Query */
            derived_query: {
                [key: string]: string | null;
            };
            /** Error */
            error: string | null;
            /** Error Code */
            error_code: string | null;
            /** Found */
            found: boolean;
            /** From Archive */
            from_archive: number;
            /** Index */
            index: number;
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Methods */
            methods: string[];
            /** Name */
            name: string;
            /** Response Ids */
            response_ids: string[];
            /** Total */
            total: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "item";
        };
        /**
         * HarvestItemResponse
         * @description The outcome of fetching Last.fm data for one item.
         */
        HarvestItemResponse: {
            /** Alternatives */
            alternatives: components["schemas"]["SearchAlternativeView"][];
            /** Derived */
            derived?: {
                [key: string]: number;
            } | null;
            /** Derived Query */
            derived_query: {
                [key: string]: string | null;
            };
            /** Error */
            error: string | null;
            /** Error Code */
            error_code: string | null;
            /** Found */
            found: boolean;
            /** From Archive */
            from_archive: number;
            /** Item Id */
            item_id: string;
            /** Kind */
            kind: string;
            /** Methods */
            methods: string[];
            /** Name */
            name: string;
            /** Response Ids */
            response_ids: string[];
        };
        /**
         * HarvestReindexedEvent
         * @description The derived layer was rebuilt, which is what makes the fetched data usable.
         */
        HarvestReindexedEvent: {
            /** Albums */
            albums: number;
            /** Aliases */
            aliases: number;
            /** Artists */
            artists: number;
            /** Entity Tags */
            entity_tags: number;
            /** Expected No Envelope */
            expected_no_envelope: number;
            /** Observations */
            observations: number;
            /** Response Bodies */
            response_bodies: number;
            /** Similarities */
            similarities: number;
            /** Tag Edges */
            tag_edges: number;
            /** Tracks */
            tracks: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reindexed";
            /** Unexpected Shapes */
            unexpected_shapes: number;
        };
        /** HarvestRequest */
        HarvestRequest: {
            /**
             * Reindex
             * @description rebuild the derived layer so candidates can resolve
             * @default true
             */
            reindex: boolean;
            /**
             * Search Fallback
             * @default true
             */
            search_fallback: boolean;
            /**
             * @default {
             *       "kind": "artist",
             *       "limit": 50,
             *       "missing_metadata": false
             *     }
             */
            selection: components["schemas"]["HarvestSelection"];
        };
        /** HarvestSearchAlternative */
        HarvestSearchAlternative: {
            /** Artist */
            artist: string | null;
            /** Listeners */
            listeners: number | null;
            /** Name */
            name: string;
            /** Url */
            url: string | null;
        };
        /**
         * HarvestSelection
         * @description Which items to fetch for. Mirrors the library browse parameters.
         */
        HarvestSelection: {
            /**
             * Ids
             * @description explicit item ids, if known
             */
            ids?: string[] | null;
            /**
             * Kind
             * @default artist
             * @enum {string}
             */
            kind: "artist" | "album" | "song";
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Missing Metadata
             * @description only items lacking genres, provider ids or an overview
             * @default false
             */
            missing_metadata: boolean;
            /** Parent Id */
            parent_id?: string | null;
            /** Search */
            search?: string | null;
        };
        /** HarvestSummaryEvent */
        HarvestSummaryEvent: {
            /** Found */
            found: number;
            /** Items */
            items: number;
            /** Missing */
            missing: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "summary";
        };
        /** InfoResponse */
        InfoResponse: {
            /** App Version */
            app_version: string;
            archive: components["schemas"]["ArchiveInfo"];
            jellyfin: components["schemas"]["JellyfinInfo"];
            lastfm: components["schemas"]["LastfmInfo"];
        };
        /** ItemSummary */
        ItemSummary: {
            /** Album */
            album?: string | null;
            /** Album Artist */
            album_artist?: string | null;
            /** Child Count */
            child_count?: number | null;
            /**
             * Genres
             * @default []
             */
            genres: string[];
            /**
             * Has Overview
             * @default false
             */
            has_overview: boolean;
            /**
             * Has Provider Ids
             * @default false
             */
            has_provider_ids: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "artist" | "album" | "song";
            /** Name */
            name: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Year */
            year?: number | null;
        };
        /** ItemSummaryPage */
        ItemSummaryPage: {
            /**
             * Filtered Client Side
             * @default false
             */
            filtered_client_side: boolean;
            /** Items */
            items: components["schemas"]["ItemSummary"][];
            /**
             * Order
             * @enum {string}
             */
            order: "asc" | "desc";
            /** Page Size */
            page_size: number;
            /**
             * Sort
             * @enum {string}
             */
            sort: "name" | "sort_name" | "date_added" | "year" | "random";
            /** Start Index */
            start_index: number;
            /** Total */
            total: number;
        };
        /** JellyfinInfo */
        JellyfinInfo: {
            /** Elevated */
            elevated?: boolean | null;
            /** Error */
            error?: string | null;
            /** Key Configured */
            key_configured: boolean;
            /** Reachable */
            reachable: boolean;
            /** Server Name */
            server_name?: string | null;
            /** Version */
            version?: string | null;
        };
        /** LastfmInfo */
        LastfmInfo: {
            /** Api Root */
            api_root: string;
            /** Configured */
            configured: boolean;
        };
        /** LibraryInfo */
        LibraryInfo: {
            /** Id */
            id: string | null;
            /**
             * Locations
             * @default []
             */
            locations: string[];
            /** Name */
            name: string;
        };
        /** PartitionUsage */
        PartitionUsage: {
            /** Name */
            name: string;
            /** Rows */
            rows: number;
        };
        /** ReadMetricsView */
        ReadMetricsView: {
            /** Decisions */
            decisions: number;
            /** Hit Ratio */
            hit_ratio: number | null;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
            /** Note */
            note: string;
            /** Scope */
            scope: string;
        };
        /** ReindexCounts */
        ReindexCounts: {
            /** Albums */
            albums: number;
            /** Aliases */
            aliases: number;
            /** Artists */
            artists: number;
            /** Entity Tags */
            entity_tags: number;
            /** Expected No Envelope */
            expected_no_envelope: number;
            /** Observations */
            observations: number;
            /** Response Bodies */
            response_bodies: number;
            /** Similarities */
            similarities: number;
            /** Tag Edges */
            tag_edges: number;
            /** Tracks */
            tracks: number;
            /** Unexpected Shapes */
            unexpected_shapes: number;
        };
        /** ReindexRequest */
        ReindexRequest: {
            /**
             * Dry Run
             * @description Derive and report without writing. Defaults to true: a rebuild that writes should be an explicit choice, not an accident.
             * @default true
             */
            dry_run: boolean;
            /** Only */
            only?: ("artist" | "album" | "track" | "tag" | "similar" | "alias") | null;
        };
        /** ReindexResponse */
        ReindexResponse: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            counts: components["schemas"]["ReindexCounts"];
            /** Dry Run */
            dry_run: boolean;
            /** Duration Ms */
            duration_ms: number;
        };
        /**
         * SearchAlternativeView
         * @description A Last.fm search hit, offered when the derived query missed.
         *
         *     A miss that says only "not found" leaves the operator with nothing to do; these give
         *     them something to pick.
         */
        SearchAlternativeView: {
            /** Artist */
            artist: string | null;
            /** Listeners */
            listeners: number | null;
            /** Name */
            name: string;
            /** Url */
            url: string | null;
        };
        /** SnapshotListResponse */
        SnapshotListResponse: {
            /** Count */
            count: number;
            /** Item Id */
            item_id: string;
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotSummary"][];
        };
        /** SnapshotSummary */
        SnapshotSummary: {
            /** Created At */
            created_at: string | null;
            /** Etag */
            etag: string | null;
            /** Field Count */
            field_count: number;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
            /** Source Op */
            source_op: string;
        };
        /** TagPolicyRequest */
        TagPolicyRequest: {
            /** Extra Blacklist */
            extra_blacklist?: string[];
            /**
             * Genre Limit
             * @default 5
             */
            genre_limit: number;
            /**
             * Min Count
             * @default 0
             */
            min_count: number;
            /**
             * Style Limit
             * @default 10
             */
            style_limit: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    archive_aliases_api_archive_aliases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveAliasListResponse"];
                };
            };
        };
    };
    archive_diagnose_api_archive_diagnose_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    archive_entities_api_archive_entities_get: {
        parameters: {
            query?: {
                kind?: "artist" | "album" | "track";
                /** @description only entities carrying this tag */
                tag?: string | null;
                search?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveEntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_entity_api_archive_entities__kind___entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "artist" | "album" | "track";
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveEntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_reindex_api_archive_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReindexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_stats_api_archive_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveStatsResponse"];
                };
            };
        };
    };
    archive_tags_api_archive_tags_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveTagListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_apply_api_bulk_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApplyRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events, one frame per item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkItemEvent"] | components["schemas"]["BulkAppliedEvent"] | components["schemas"]["BulkFailedEvent"] | components["schemas"]["BulkRevertedEvent"] | components["schemas"]["BulkSummaryEvent"] | components["schemas"]["BulkErrorEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_diff_api_bulk_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkDiffRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events, one frame per item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkItemEvent"] | components["schemas"]["BulkAppliedEvent"] | components["schemas"]["BulkFailedEvent"] | components["schemas"]["BulkRevertedEvent"] | components["schemas"]["BulkSummaryEvent"] | components["schemas"]["BulkErrorEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_bulk_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkJobListResponse"];
                };
            };
        };
    };
    bulk_revert_api_bulk__batch_id__revert_post: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events, one frame per item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkItemEvent"] | components["schemas"]["BulkAppliedEvent"] | components["schemas"]["BulkFailedEvent"] | components["schemas"]["BulkRevertedEvent"] | components["schemas"]["BulkSummaryEvent"] | components["schemas"]["BulkErrorEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harvest_batch_api_harvest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HarvestRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events, one frame per harvested item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestItemEvent"] | components["schemas"]["HarvestSummaryEvent"] | components["schemas"]["HarvestReindexedEvent"] | components["schemas"]["HarvestErrorEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    info_api_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    items_api_items_get: {
        parameters: {
            query?: {
                kind?: "artist" | "album" | "song";
                parent_id?: string | null;
                search?: string | null;
                start_index?: number;
                page_size?: number;
                /** @description field to order by */
                sort?: "name" | "sort_name" | "date_added" | "year" | "random";
                /** @description direction; ignored by `random` */
                order?: "asc" | "desc";
                /** @description Jellyfin's own filter: true returns only items with an overview, false only those without. Applied by the server, so `total` reflects it. */
                has_overview?: boolean | null;
                /** @description Jellyfin's own filter: exact production year. */
                year?: number | null;
                /** @description only items lacking genres, provider ids or an overview. Jellyfin cannot express this for music, so it filters the fetched page and `total` stays unfiltered -- see `filtered_client_side`. */
                missing_metadata?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSummaryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_states_api_items_states_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_apply_api_items__item_id__apply_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_candidates_api_items__item_id__candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CandidatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_diff_api_items__item_id__diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    harvest_one_api_items__item_id__harvest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_harvest_one_api_items__item_id__harvest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_item_api_items__item_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_snapshots_api_items__item_id__snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_state_api_items__item_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    libraries_api_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryInfo"][];
                };
            };
        };
    };
    revert_api_snapshots__snapshot_id__revert_post: {
        parameters: {
            query?: {
                /** @description must be true */
                confirm?: boolean;
            };
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
